### ISSUE TITLE
Erro ao rodar python setup.py build

### ISSUE THREAD

**Issue by flaudemir79** [paulopinda/python-nbiobsp#2]
Bom dia
 
Estou seguindo seu script de instalação, porém estou encontrando problemas.

Quais os pré-requisitos para instalação do mesmo? Versão do python, etc.
Já instalei o **python 3.5.4** e mesmo assim não encontra o arquivo "boost_python-py35".

Meu cenáro é Debian 8 + Python 3.5.4

running build
running build_ext
building 'pynbiobsp' extension
g++ -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -I/home/demir/Downloads/BIOMETRIA/bioenv3/include/python3.4m -c pynbiobsp.cpp -o build/temp.linux-x86_64-3.4/pynbiobsp.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-g++ -shared -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/pynbiobsp.o -lboost_python-py35 -lNBioBSP -o build/lib.linux-x86_64-3.4/pynbiobsp.cpython-34m.so
**/usr/bin/ld: cannot find -lboost_python-py35**
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-g++' failed with exit status 1

**Comment by paulo-social** [comment]
Olá,

Já instalei em versões 2.x e 3.x, este problema ocorre por não está encontrando a biblioteca Boost.Python para linkar no momento da build. No Ubuntu eu verificaria o diretório /usr/lib/x86_64-linux-gnu, se tem os arquivos: libboost_python-py35.so e libboost_python-py35.a.

Poderia me enviar o resultado de: ls -l /usr/lib/x86_64-linux-gnu/libboost_py*

**Comment by flaudemir79** [comment]
Já procurei essa biblioteca lá e realmente não existe!!!

Existe:
libboost_python-py27 - Do python 2.7
libboost_python-py34 - Do python 3.4

mas a do python 3.5 não existe e na instalação do python 3.5 não veio tb!

Atenciosamente,

___________________________
*Flaudemir F. Pinheiro*
(85) 9.9900-1312

2017-11-22 17:16 GMT-03:00 Paulo Roberto Silva <notifications@github.com>:

**Comment by paulo-social** [comment]
Então no seu caso, você vai ter que ser "boost_python-py34" conforme está descrito no README.md:

"Need change BOOSTPYTHON_VERSION in the setup.py to your version Python."

Tenta alterar no setup.py, BOOSTPYTHON_VERSION = 'boost_python-py35' para BOOSTPYTHON_VERSION = 'boost_python-py34'.

Fazendo essa alteração tenta fazer a build novamente por favor.

**Comment by flaudemir79** [comment]
Ok - Vou tentar amanhã, pois, é no computador da empresa.

De qualquer forma, já lhe agradeço a atenção e te retorno com o resultado.

Atenciosamente,

___________________________
*Flaudemir F. Pinheiro*
(85) 9.9900-1312

2017-11-22 18:44 GMT-03:00 Paulo Roberto Silva <notifications@github.com>:

**Comment by paulo-social** [comment]
Ok, aguardo então, até mais.

**Comment by flaudemir79** [comment]
Deu ok ao trocar o valor da variável em config.py.


Ao testar, me deparei com o erro.

>>> import pynbiobsp as pnbio
>>> pnbio.init()
True
>>> fir1 = pnbio.capture(5000)
*Falha de segmentação*

Vou substituir o leitor para testar e te retorno!



___________________________
*Flaudemir F. Pinheiro*
(85) 9.9900-1312

2017-11-22 19:16 GMT-03:00 Paulo Roberto Silva <notifications@github.com>:

**Comment by flaudemir79** [comment]
Obs: ao trocar o  valor da variável em config.py.

Rodado o Build e o Install para depois fazer o teste!


___________________________
*Flaudemir F. Pinheiro*
(85) 9.9900-1312

Em 23 de novembro de 2017 11:48, Flaudemir Pinheiro <demir@fpinheiro.com>
escreveu:

**Comment by paulo-social** [comment]
Estou atualizando o módulo, estou retirando o Boost.Python e migrando para Pybind11. Vai facilitar instalação.

**Comment by flaudemir79** [comment]
A instalação parece que deu certo. Não gerou erro!

Gerou erro quando fui executar o programa teste.py

Em 23 de nov de 2017 2:11 PM, "Paulo Roberto Silva" <
notifications@github.com> escreveu:

Estou atualizando o módulo, estou retirando o Boost.Python e migrando para
Pybind11. Vai facilitar instalação.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/paulopinda/python-nbiobsp/issues/2#issuecomment-346656578>,
or mute the thread

**Comment by paulo-social** [comment]
Atualizei o módulo retirando o Boost.Python e migrei pra Pybind11, e atualizei a documentação. Qual equipamento está usando? Att

**Comment by flaudemir79** [comment]
i5 com 8GB, leitor NITGEN Hamster II

Em 26 de nov de 2017 2:17 PM, "Paulo Roberto Silva" <
notifications@github.com> escreveu:

Atualizei o módulo retirando o Boost.Python e migrei pra Pybind11, e
atualizei a documentação. Qual equipamento está usando? Att

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/paulopinda/python-nbiobsp/issues/2#issuecomment-347019809>,
or mute the thread

**Comment by paulo-social** [comment]
Tenta instalar usando:

pip install pynbiobsp

Agora coloquei no Pypi também.

**Comment by paulo-social** [comment]
Lembrando que quando escrevi esse módulo foi utilizando Hamster III, não sei se funcionaria no Hamster II. Se funcionar me avisa pra eu por no README.md, por favor.

**Comment by flaudemir79** [comment]
Me enganei, na verdade o nosso é o:

Marca: Nitgen
Modelo: Hamster DX HFDU04

Não consegui fazer funcionar, mas muito obrigado pela atenção!!!
Infelizmente, voltando para o mundo WINDOWS!

Atenciosamente,



___________________________
*Flaudemir F. Pinheiro*
(85) 9.9900-1312

2017-11-27 0:16 GMT-03:00 Paulo Roberto Silva <notifications@github.com>:

**Comment by paulo-social** [comment]
Ok
