### ISSUE TITLE
Installing on windows 10 gives error with python 3 

### ISSUE THREAD

**Issue by MahendraNG** [paulopinda/python-nbiobsp#3]
Hi
I'm trying to install this library on my windows machine, but I did not get success, now after trying very hard, I suspect that this library works with Windows machine as well.

I'm getting following error

     LINK : fatal error LNK1181: cannot open input file 'NBioBSP.lib'
     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1181

if anyone has any idea then please let me know.

**Comment by paulo-social** [comment]
I don't use Windows, if you resolve send me a PR, please. 
Thanks!

**Comment by talesmm14** [comment]
Add lines in Extension

```
library_dirs=[
"C:\\Program Files\\NITGEN eNBSP x64\\SDK\\Lib\\x64",
"C:\\Program Files\\NITGEN eNBSP x64\\SDK\\Bin\\x64",
]
```
on mine it was like this

```
ext_modules = [
    Extension(
        'pynbiobsp',
        [BASE_DIR + '/src/main.cpp'],
        include_dirs=[
            get_pybind_include(),
            get_pybind_include(user=True),
            BASE_DIR + '/include/',
        ],
        library_dirs=[
            "C:\\Program Files\\NITGEN eNBSP x64\\SDK\\Lib\\x64",
            "C:\\Program Files\\NITGEN eNBSP x64\\SDK\\Bin\\x64",
        ],
        libraries=['NBioBSP'],
        language='c++'
    ),
]
```

**Comment by paulo-social** [comment]
Thanks @talesmm14
