### ISSUE TITLE
save FIR to database

### ISSUE THREAD

**Issue by riffelw** [paulopinda/python-nbiobsp#4]
Hi, nice job, I can use my nitgen hamster ii, finally, I develop and access door for my church, but when I try to save the FIR from pnbio.capture() when I print and I see diferente text every time when try.
How can convert this info to store in database?

**Comment by paulo-social** [comment]
Hi, I save the hash in the database. It is normal hashs to change.

**Comment by amit-tewari** [comment]
Can I save value returned from capture method in SQL database, and perform a SQL query against these values with WHERE clause to verify if another capture is a match or not?
Or I shall have to fetch each row from database and invoke 'match' method with each stored FIR?

**Comment by paulo-social** [comment]
Yes, this is a way.
