### ISSUE TITLE
cannot find -lNBioBSP

### ISSUE THREAD

**Issue by ivdrmyns** [paulopinda/python-nbiobsp#5]
Hi 
I'm trying to install this on ubuntu 16.04. But when I try "pip install pynbiobsp", I get the error "/usr/bin/ld: cannot find -lNBioBSP".

Does anyone has an idea how to solve this?

**Comment by paulo-social** [comment]
Here https://github.com/paulopinda/python-nbiobsp/tree/master/utils/hamster-iii
