### ISSUE TITLE
finger print error: cannot access '/dev/ngstar[0-9]*'  

### ISSUE THREAD

**Issue by riffelw** [paulopinda/python-nbiobsp#6]
Hi, i have this problem, recurrently, when pass some time the fingerprint has the two led ligth low, and when try again to capture fingerprint said this error: cannot access '/dev/ngstar[0-9]*' , and not work again, I try to reset the usb, and reinstall the driver but not work again, I need to reinstall all the computer again, to use, I bought a new finger print, the same, and append again and again  the same thing. PLEASE HELP!

**Comment by paulo-social** [comment]
Check the driver requirements and follow these instructions:
http://help.bioenabletech.com/showthread.php/513-Using-Hamster-on-Linux
