### ISSUE TITLE
Erro na Instalação (resolvido)

### ISSUE THREAD

**Issue by saldorflorin** [paulopinda/python-nbiobsp#9]
Primeiro, agradeço por disponibilizar o seu projeto. Esse servirá de grande ajuda para um projeto que estou bolando.

Na hora de instalar aparece esse erro, você tem alguma solução para isso??

Criando biblioteca build\temp.win32-3.9\Release\Users\salva\AppData\Local\Programs\Python\Python39-32\Lib\site-packages\pynbiobsp/src\pynbiobsp.cp39-win32.lib e objeto build\temp.win32-3.9\Release\Users\salva\AppData\Local\Programs\Python\Python39-32\Lib\site-packages\pynbiobsp/src\pynbiobsp.cp39-win32.exp
main.obj : error LNK2001: símbolo externo não resolvido _NBioAPI_GetTextFIRFromHandle
main.obj : error LNK2001: símbolo externo não resolvido _NBioAPI_Init
main.obj : error LNK2001: símbolo externo não resolvido _NBioAPI_CloseDevice
main.obj : error LNK2001: símbolo externo não resolvido _NBioAPI_Capture
main.obj : error LNK2001: símbolo externo não resolvido _NBioAPI_OpenDevice
main.obj : error LNK2001: símbolo externo não resolvido _NBioAPI_VerifyMatch
main.obj : error LNK2001: símbolo externo não resolvido _NBioAPI_Terminate
build\lib.win32-3.9\pynbiobsp.cp39-win32.pyd : fatal error LNK1120: 7 externo não resolvidos

**Comment by paulo-social** [comment]
Olá, o módulo foi pensando para ser executado em Linux, não em Windows. Porém é possível enviar um PR com as funcionalidades que deseja, se quiser colaborar. Obrigado!
